applications:
  blogs_app:
    source:
      root: "blogs"
    type: "python:3.14.4"

    mounts:
      "logs":
        source: local
        source_path: logs

    hooks:
      build: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_remote.txt
        mkdir logs
        python manage.py collectstatic
        rm -rf logs
      deploy: |
        python manage.py migrate

    relationships:
      database: "db:postgresql"

services:
  db:
    type: postgresql:12

routes:
  "https://{default}/":
    type: upstream
    upstream: "blogs_app:http"
  "https://www.{default}/":
    type: redirect
    to: "https://{default}/"
